version: '3'
services:
  database:
    image: postgres:13
    container_name: my_postgres_database
    restart: always
    volumes:
        - ./data:/var/lib/postgresql/data
        - ./my-postgres.conf:/etc/postgresql/postgresql.conf
        - ./my-pg_hba.conf:/etc/postgresql/pg_hba.conf
        - ./postgresslave:/tmp/postgresslave
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'