version: '3'
services:
  database:
    image: postgres:13
    container_name: pg_master_db
    restart: always
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - ./data/tmp/:/tmp
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - 'POSTGRES_PASSWORD=123123'
      - 'POSTGRES_DB=master_db'
