# docker-compose.yaml
version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8000:8080
     - 50000:50000
    container_name: jenkins
    volumes:
     - ./data/jenkins_home:/var/jenkins_home
     - ./data/docker.sock:/var/run/docker.sock
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5rNHaZAgJ+1WaUFFgKODmWYhCco385a87gdBVsx94MhcciLCscIO0mshHQhPXGFBYzKuGponwSX9On/qFdTwjKaEVwgKndduhylnD9Mzni/CbrvYFqC/3AcLogZPkCwvDA9tu0T9PijDm/8F0Z57PLXCIVtX/lpfXAOwfyd4HI/9yC8i7pdipESnN4XFSssbJCcX+Sm6BLDEcMX/BbLngOhiikQZqfkonQEeoNlo+S3Kjb+coQCXBit5/BbLOriTHrxd244TdAI7DxT+VMSla9TDpZm5wthUYBi19K2cLgv0JnXcmFwl5Djt3f7DO0zKh9HQZHQ/uwzRcwG8SD14uCPgC+ih25Tp+THMf00oVrh/h4G4O0ZIbMA68YpI2b1dhWGyTpghVFmwOrGYbSuu8xSBYNqqZHMr+AnRWDzj8FmHXzbZfSfO2BDrNNmcO72/weZhWP47tDObiRUBqK/h+714sbLjYB9RnKyUAKq9025YRq8DCT3QDtlkc6WhUXQk= armand@DESKTOP-GHU558L