version: '2'
networks:
  backend:
    external:
      name: dockernetwork

services:
  master-postgres:
    restart: always
    image: postgres:13
    volumes:
      - ./data/pgdata/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
        backend:
            ipv4_address: 172.18.0.101
    logging:
      options:
        max-size: "100m"
