version: '3'
services:
  database:
    image: postgres:13
    container_name: my_postgres_database_slave
    restart: always
    volumes:
        - ./data:/var/lib/postgresql/data
        - ./my-postgres.conf:/etc/postgresql/postgresql.conf
        - ./my-pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'